/*+********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ********************************************************************************/

function fieldExpressionPopup(moduleName, $){

	var format = fn.format;
	var opType;

	var ownersList = {};

	function close(){
		$('#editpopup').css('display', 'none');
		$('#editpopup_expression').text('');
	}

	function show(){
		$('#editpopup').css('display', 'block');
		center($('#editpopup'));
	}

	function center(el){
		el.css({
			position: 'absolute'
		});
		el.css({
			width: '650px'
		});
		placeAtCenter(el.get(0));
	}

	function showElement(ele, displaytype) {
		if(displaytype == null || displaytype == '' || displaytype == 'undefined') {
			displaytype = 'inline';
		}

		if(typeof ele.css != 'function') {
			ele.style.display = displaytype;
		} else {
			ele.css('display', displaytype);
		}
	}

	function hideElement(ele) {
		if(typeof ele.css != 'function') {
			ele.style.display = 'none';
		} else {
			ele.css('display', 'none');
		}
	}

	function map(fn, list){
		var out = [];
		$.each(list, function(i, v){
			out[out.length]=fn(v);
		});
		return out;
	}

	function implode(sep, arr){
		var out = "";
		$.each(arr, function(i, v){
			out+=v;
			if(i<arr.length-1){
				out+=sep;
			}
		});
		return out;
	}

	var filter = fn.filter;
	var vtinst = new VtigerWebservices("webservice.php");
	var dict = fn.dict;
	var reduceR = fn.reduceR;
	var concat = fn.concat;
	var contains = fn.contains;
	function diff(reflist, list) {
		var out = [];
		$.each(list, function(i, v) {
			if(contains(reflist, v)) {
				out.push(v);
			}
		});
		return out;
	}

	//This is a wrapper to handle webservice errors.
	function handleError(fn){
		return function(status, result){
			if(status){
				fn(result);
			}else{
				errorDialog('Failure:'+result);
			}
		};
	}

	//Get an array containing the the description of a module and all modules
	//refered to by it. This is passed to callback.
	function getDescribeObjects(accessibleModules, moduleName, callback){
		vtinst.describeObject(moduleName, handleError(function(result){
			var parent = referencify(result);
			var fields = parent['fields'];
			var referenceFields = filter(function(e){
				return e['type']['name']=='reference';},
			  fields);
			var referenceFieldModules =
				map(
					function(e){
						return e['type']['refersTo'];
					},
					referenceFields
				);
			function union(a, b){
			  var newfields = filter(function(e){return !contains(a, e);}, b);
			  return a.concat(newfields);
			}
			var relatedModules = reduceR(union, referenceFieldModules, [parent['name']]);

			// Remove modules that is no longer accessible
			relatedModules = diff(accessibleModules, relatedModules);

			function executer(parameters){
				var failures = filter(function(e){return e[0]==false;}, parameters);
				if(failures.length!=0){
					var firstFailure = failures[0];
					callback(false, firstFailure[1]);
				}else{
					var moduleDescriptions = map(function(e){
						return referencify(e[1]);},
					  parameters);
					var modules = dict(map(function(e){
						  return [e['name'], e];},
						moduleDescriptions));
					callback(true, modules);
				}
			}
			var p = parallelExecuter(executer, relatedModules.length);
			$.each(relatedModules, function(i, v){
				p(function(callback){vtinst.describeObject(v, callback);});
			});
		}));
	}
	function fillSelectBox(id, modules, parentModule, filterPred){
		if(filterPred==null){
			filterPred = function(){
				return true;
			};
		}
		var parent = modules[parentModule];
		var fields = parent['fields'];

		function filteredFields(fields){
			return filter(
				function(e){
					var fieldCheck = !contains(['autogenerated', 'reference', 'owner', 'multipicklist', 'password'], e.type.name);
					var predCheck = filterPred(e);
					return fieldCheck && predCheck;
				},
				fields
			);
		}
		var parentFields = map(function(e){return[e['name'],e['label']];}, filteredFields(parent['fields']));

		var referenceFieldTypes = filter(function(e){
				return (e['type']['name']=='reference');
			},parent['fields']
		);

		var moduleFieldTypes = {};
		$.each(modules, function(k, v){
				moduleFieldTypes[k] = dict(map(function(e){return [e['name'], e['type']];},filteredFields(v['fields'])));
			}
		);

		function getFieldType(fullFieldName){
			var group = fullFieldName.match(/(\w+) : \((\w+)\) (\w+)/);
			if(group==null){
				var fieldModule = moduleName;
				var fieldName = fullFieldName;
				}else{
					var fieldModule = group[2];
				var fieldName = group[3];
			}
			return moduleFieldTypes[fieldModule][fieldName];
		}

		function fieldReferenceNames(referenceField){
			var name = referenceField['name'];
			var label = referenceField['label'];
			function forModule(moduleName){
				// If module is not accessible return no field information
				if(!contains(accessibleModulesInfo, moduleName)) return [];

				return map(function(field){
					return ['('+name+' : '+'('+moduleName+') '+field['name']+')',label+' : '+'('+modules[moduleName]['label']+') '+field['label']];
					},
					filteredFields(modules[moduleName]['fields']));
			}
			return reduceR(concat,map(forModule,referenceField['type']['refersTo']),[]);
		}

		var referenceFields = reduceR(concat,map(fieldReferenceNames,referenceFieldTypes), []);
		var fieldLabels = dict(parentFields.concat(referenceFields));
		var select = $('#'+id);
		var optionClass = id+'_option';
		$.each(fieldLabels, function(k, v){
			select.append('<option class="'+optionClass+'" '+ 'value="'+k+'">' + v + '</option>');
		});

	}

	//Convert user type into reference for consistency in describe objects
	//This is done inplace
	function referencify(desc){
		var fields = desc['fields'];
		for(var i=0; i<fields.length; i++){
			var field = fields[i];
			var type = field['type'];
			if(type['name']=='owner'){
				type['name']='reference';
				type['refersTo']=['Users'];
			}
		}
		return desc;
	}

	function handleExpressionType(ele) {
		var value = ele.attr('value');
		var helpElements = $('.layerPopup .helpmessagebox');
		$.each(helpElements, function(index, helpElement) {
			hideElement(helpElement);
		});
		if(value == 'fieldname') {
			showElement($('#fieldname_help'), 'block');
			showElement($('#editpopup_fieldnames'));
			hideElement($('#editpopup_functions'));
			setFieldType('string')(opType);
		} else if(value == 'expression') {
			showElement($('#expression_help'), 'block');
			showElement($('#editpopup_fieldnames'));
			showElement($('#editpopup_functions'));
			setFieldType('string')(opType);
		} else {
			showElement($('#text_help'), 'block');
			hideElement($('#editpopup_fieldnames'));
			hideElement($('#editpopup_functions'));

			var fieldType = $('#editpopup_field_type').attr('value');
			setFieldType(fieldType)(opType);
		}
	}

	$('#editpopup_close').bind('click', close);
	$('#editpopup_save').bind('click', function(){
		var expression = $('#editpopup_expression').attr('value');
		expression = expression.replace(/<script(.|\s)*?\/script>/g, "");
		expression = expression.replace(/\n/g, "<br>");  // convert \n to <br> for saving

		var fieldElementId = $("#editpopup_field").attr('value');
		$("#"+fieldElementId).attr('value', expression);

		var expressionType = $("#editpopup_expression_type").attr('value');
		$("#"+fieldElementId+"_type").attr('value', expressionType);

		close();
	});

	$('#editpopup_cancel').bind('click', close);

	$('#editpopup_expression_type').bind('change', function() {
		handleExpressionType($(this));
	});

	$('#editpopup_fieldnames').bind('change', function(){
		var textarea = $('#editpopup_expression').get(0);
		var value = '$'+$(this).attr('value') + ' ';
		if(value == '$ ') return true;
		//http://alexking.org/blog/2003/06/02/inserting-at-the-cursor-using-javascript
		if (document.selection) {
			textarea.focus();
			var sel = document.selection.createRange();
			sel.text = value;
			textarea.focus();
		}else if (textarea.selectionStart || textarea.selectionStart == '0') {
			var startPos = textarea.selectionStart;
			var endPos = textarea.selectionEnd;
			var scrollTop = textarea.scrollTop;
			textarea.value = textarea.value.substring(0, startPos)
			+ value
			+ textarea.value.substring(endPos,
				textarea.value.length);
			textarea.focus();
			textarea.selectionStart = startPos + value.length;
			textarea.selectionEnd = startPos + value.length;
			textarea.scrollTop = scrollTop;
		}	else {
			textarea.value += value;
			textarea.focus();
		}
		// Reset the selected option (to enable next selection)
		this.value = '';

	});

	function setFieldType(fieldType){

		function forPicklist(opType){
			var value = $("#editpopup_expression");
			var options = implode('',
				map(function (e){
					return '<option value="'+e.value+'">'+e.label+'</option>';
				},
				opType['picklistValues'])
				);
			value.replaceWith('<select id="editpopup_expression" class="value">'+options+'</select>');
		}

		function forInteger(opType){
			var value = $("#editpopup_expression");
			value.replaceWith('<input type="text" id="editpopup_expression" value="0" class="value">');
		}
		function forOwnerField(opType){
			var value = $("#editpopup_expression");
			var options = implode('',
				map(function (e){
					return '<option value="'+e.value+'">'+e.label+'</option>';
				},
				ownersList)
				);
			value.replaceWith('<select id="editpopup_expression" class="value">'+options+'</select>');
		}
		function forDateField(opType) {
			var value = $("#editpopup_expression");
			value.replaceWith('<input type="text" id="editpopup_expression" class="value"> \
								<img border=0 src="themes/softed/images/btnL3Calendar.gif" alt="SET DATE" title="SET DATE" id="jscal_trigger_editpopup_expression">');
			Calendar.setup (
				{inputField : "editpopup_expression", ifFormat : "%Y-%m-%d", showsTime : false, button : "jscal_trigger_editpopup_expression", singleClick : true, step : 1}
			);
		}
		function forTimeField(opType){ 
			var value = $("#editpopup_expression");
			value.replaceWith('<input type="text" id="editpopup_expression" value="0" class="value">');
		}
		function forDateTimeField(opType) {
			var value = $("#editpopup_expression");
			value.replaceWith('<input type="text" id="editpopup_expression" class="value" readonly> \
								<img align="absmiddle" border=0 src="themes/softed/images/btnL3Calendar.gif" alt="SET DATE" title="SET DATE" id="jscal_trigger_editpopup_expression">');
			Calendar.setup (
				{inputField : "editpopup_expression", ifFormat : "%Y-%m-%d", showsTime : true, button : "jscal_trigger_editpopup_expression", singleClick : true, step : 1}
			);
		}
		var functions = {
			string:function(opType){
				var value = $("#editpopup_expression");
				value.replaceWith('<textarea name="Name" rows="10" cols="50" id="editpopup_expression"></textarea>');
			},
			'boolean': function(opType){
				var value = $("#editpopup_expression");
				value.replaceWith(
					'<select id="editpopup_expression" value="true" class="value"> \
						<option value="true:boolean">True</option>\
						<option value="false:boolean">False</option>\
					</select>');
			},
			integer: forInteger,
			picklist: forPicklist,
			multipicklist: forPicklist,
			owner: forOwnerField,
			date: forDateField,
			datetime: forDateTimeField,
			time: forTimeField 
		};

		if($('#jscal_trigger_editpopup_expression'))  $('#jscal_trigger_editpopup_expression').remove();
		var ret = functions[fieldType];
		if(ret==null){
			ret = functions['string'];
		}
		return ret;
	}

	$.get('index.php', {
		module:'com_vtiger_workflow',
		action:'com_vtiger_workflowAjax',
		file:'WorkflowComponents',
		ajax:'true',
		modulename:moduleName,
		mode:'getownerslist'
	},
	function(result){
		result = JSON.parse(result);
		ownersList = result;
	}
	);

	$.get('index.php', {
		module:'com_vtiger_workflow',
		action:'com_vtiger_workflowAjax',
		file:'WorkflowComponents',
		ajax:'true',
		modulename:moduleName,
		mode:'getfunctionsjson'
	},
	function(result){
		result = JSON.parse(result);
		var functions = $('#editpopup_functions');
		$.each(result, function(label, template){
			functions.append(format('<option value="%s">%s</option>', template, label));
		});
		$('#editpopup_functions').bind('change', function(){
			var textarea = $('#editpopup_expression').get(0);
			var value = $(this).attr('value');
			//http://alexking.org/blog/2003/06/02/inserting-at-the-cursor-using-javascript
			if (document.selection) {
				textarea.focus();
				var sel = document.selection.createRange();
				sel.text = value;
				textarea.focus();
			}else if (textarea.selectionStart || textarea.selectionStart == '0') {
				var startPos = textarea.selectionStart;
				var endPos = textarea.selectionEnd;
				var scrollTop = textarea.scrollTop;
				textarea.value = textarea.value.substring(0, startPos)
				+ value
				+ textarea.value.substring(endPos,
					textarea.value.length);
				textarea.focus();
				textarea.selectionStart = startPos + value.length;
				textarea.selectionEnd = startPos + value.length;
				textarea.scrollTop = scrollTop;
			}else {
				textarea.value += value;
				textarea.focus();
			}
			// Reset the selected option (to enable next selection)
			this.value = '';

		});

	}
	);


	return {
		create: show,
		edit: function(fieldelementid, expression, fieldtype){
			$("#editpopup_field").attr('value', fieldelementid);
			$("#editpopup_field_type").attr('value', fieldtype.name);

			opType = fieldtype;
			var expressionTypeElement = $("#"+fieldelementid+"_type");
			var expressionType = expressionTypeElement.attr('value');
			if(expressionType != '') {
				$("#editpopup_expression_type").attr('value', expressionTypeElement.attr('value'));
			} else {
				$("#editpopup_expression_type").attr('value', 'rawtext');
			}
			handleExpressionType(expressionTypeElement);
			expression = expression.replace(/<br\s*\/?>/mg,"\n");  // convert <br> to \n for easy editing
			if(expression != '') {
				$("#editpopup_expression").attr('value', expression);
			}
			$("#editpopup_expression").focus();
			show();
		},
		close:close,
		setModule: function(moduleName){
			vtinst.extendSession(handleError(function(result){
				vtinst.listTypes(handleError(function(accessibleModules) {
					accessibleModulesInfo = accessibleModules;
					getDescribeObjects(accessibleModules, moduleName, handleError(function(modules){
						fillSelectBox('editpopup_fieldnames', modules, moduleName);
					}));
				}));
			}));
		}
	};
}


