/*+********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ********************************************************************************/
function WhatsappTask($) {
	var map = fn.map;
	var dict = fn.dict;
	var filter = fn.filter;
	var reduceR = fn.reduceR;
	var parallelExecuter = fn.parallelExecuter;
	var contains = fn.contains;
	var concat = fn.concat;
	var vtinst = new VtigerWebservices('webservice.php');

	function handleError(fn) {
		return function (status, result) {
			if (status) {
				fn(result);
			} else {
				errorDialog('Failure:'+result);
			}
		};
	}

	function referencify(desc) {
		var fields = desc['fields'];
		for (var i=0; i<fields.length; i++) {
			var field = fields[i];
			var type = field['type'];
			if (type['name']=='owner') {
				type['name']='reference';
				type['refersTo']=['Users'];
			}
		}
		return desc;
	}

	function diff(reflist, list) {
		var out = [];
		$.each(list, function (i, v) {
			if (contains(reflist, v)) {
				out.push(v);
			}
		});
		return out;
	}

	function insertAtCursor(element, value) {
		if (document.selection) {
			element.focus();
			var sel = document.selection.createRange();
			sel.text = value;
			element.focus();
		} else if (element.selectionStart || element.selectionStart == '0') {
			var startPos = element.selectionStart;
			var endPos = element.selectionEnd;
			var scrollTop = element.scrollTop;
			element.value = element.value.substring(0, startPos)
				+ value
				+ element.value.substring(
					endPos,
					element.value.length
				);
			element.focus();
			element.selectionStart = startPos + value.length;
			element.selectionEnd = startPos + value.length;
			element.scrollTop = scrollTop;
		} else {
			element.value += value;
			element.focus();
		}
	}

	function fillSelectBox(id, modules, parentModule, filterPred) {
		if (filterPred==null) {
			filterPred = function () {
				return true;
			};
		}
		var parent = modules[parentModule];
		var fields = parent['fields'];
		function filteredFields(fields) {
			return filter(
				function (e) {
					var fieldCheck = !contains(['autogenerated', 'reference', 'owner', 'multipicklist', 'password'], e.type.name);
					var predCheck = filterPred(e);
					return fieldCheck && predCheck;
				},
				fields
			);
		}
		var parentFields = map(
			function (e) {
				return [e['name'], e['label']];
			},
			filteredFields(parent['fields'])
		);

		var referenceFieldTypes = filter(function (e) {
			return (e['type']['name']=='reference');
		}, parent['fields']);

		var moduleFieldTypes = {};
		$.each(modules, function (k, v) {
			moduleFieldTypes[k] = dict(map(function (e) {
				return [e['name'], e['type']];
			}, filteredFields(v['fields'])));
		});

		function fieldReferenceNames(referenceField) {
			var name = referenceField['name'];
			var label = referenceField['label'];
			function forModule(moduleName) {
				// If module is not accessible return no field information
				if (!contains(accessibleModulesInfo, moduleName)) {
					return [];
				}

				return map(
					function (field) {
						return ['('+name+' : ('+moduleName+') '+field['name']+')', label+' : ('+moduleName+') '+field['label']];
					},
					filteredFields(modules[moduleName]['fields'])
				);
			}
			return reduceR(concat, map(forModule, referenceField['type']['refersTo']), []);
		}

		var referenceFields = reduceR(concat, map(fieldReferenceNames, referenceFieldTypes), []);
		var fieldLabels = dict(parentFields.concat(referenceFields));
		var select = $('#'+id);
		var optionClass = id+'_option';
		$.each(fieldLabels, function (k, v) {
			select.append('<option class="'+optionClass+'" value="'+k+'">' + v + '</option>');
		});
	}
	function getDescribeObjects(accessibleModules, moduleName, callback) {
		vtinst.describeObject(moduleName, handleError(function (result) {
			var parent = referencify(result);
			var fields = parent['fields'];
			var referenceFields = filter(function (e) {
				return e['type']['name']=='reference';
			}, fields);
			var referenceFieldModules =
				map(
					function (e) {
						return e['type']['refersTo'];
					},
					referenceFields
				);
			function union(a, b) {
				var newfields = filter(function (e) {
					return !contains(a, e);
				}, b);
				return a.concat(newfields);
			}
			var relatedModules = reduceR(union, referenceFieldModules, [parent['name']]);
			relatedModules = diff(accessibleModules, relatedModules);

			function executer(parameters) {
				var failures = filter(function (e) {
					return !e[0];
				}, parameters);
				if (failures.length!=0) {
					var firstFailure = failures[0];
					callback(false, firstFailure[1]);
				} else {
					var moduleDescriptions = map(function (e) {
						return referencify(e[1]);
					}, parameters);
					var modules = dict(map(function (e) {
						return [e['name'], e];
					}, moduleDescriptions));
					callback(true, modules);
				}
			}
			var p = parallelExecuter(executer, relatedModules.length);
			$.each(relatedModules, function (i, v) {
				p(function (callback) {
					vtinst.describeObject(v, callback);
				});
			});
		}));
	}

	$(document).ready(function () {
		vtinst.extendSession(handleError(function (result) {
			vtinst.listTypes(handleError(function (accessibleModules) {
				accessibleModulesInfo = accessibleModules;
				getDescribeObjects(accessibleModules, moduleName, handleError(function (modules) {
					fillSelectBox('task-fieldnames', modules, moduleName);
					$('#task-fieldnames-busyicon').hide();
					$('#task-fieldnames').show();
					$('#task-fieldnames').change(function () {
						var textarea = CKEDITOR.instances.save_content;
						var value = '$'+jQuery(this).val();
						textarea.insertHtml(value);
					});
					fillSelectBox('task_phonefields', modules, moduleName, function (e) {
						return e['type']['name']=='phone';
					});
					$('#task_phonefields').change(function () {
						var input = $($('#phone').get());
						var value = '$'+$(this).val();
						input.val(input.val()+','+value);
					});
					$('#task_timefields').change(function () {
						var textarea = CKEDITOR.instances.save_content;
						var value = '$'+$(this).val();
						textarea.insertHtml(value);
					});
					fillSelectBox('task-group_usersnames', modules, moduleName);
					$('#task-fieldnames-busyicon').hide();
					$('#task-group_usersnames').show();
					$('#task-group_usersnames').change(function () {
						var textarea = $('#save_receipent').get(0);
						var value = '$'+$(this).val();
						insertAtCursor(textarea, value);
					});
				}));
			}));
		}));
	});
}
WhatsappTask(jQuery);

var attachmentManager = {
	UploadLimit : 6,
	createUploader : function () {
		Dropzone.autoDiscover = false;
		var uploader = new Dropzone('#file-uploader', {
			url : 'index.php?module=Utilities&action=UtilitiesAjax&file=ExecuteFunctions&mode=ajax&functiontocall=saveAttachment',
			paramName: 'qqfile',
			parallelUploads: 1,
			addRemoveLinks: true,
			createImageThumbnails: true,
			dictRemoveFile: attachmentManager.i18n('JSLBL_Delete'),
			uploadMultiple: false,
			clickable: ['#file-uploader-message', '#file-uploader']
		});
		uploader.on('success', function (file, response) {
			var res = JSON.parse(response);
			file.docid = res.docid;
			file.attachid = res.attachid;
			attachmentManager.addAttachment(file.docid, this);
			var attcnt = document.getElementById('attachmentCount');
			attcnt.value = parseInt(attcnt.value) + 1;
		});
		uploader.on('removedfile', function (file) {
			attachmentManager.deleteAttachment(file.docid, this);
		});
		uploader.on('addedfile', function (file) {
			if (file.docid!=undefined) {
				attachmentManager.addAttachment(file.docid, this);
			}
		});
		return uploader;
	},
	addAttachment : function (docid, ele) {
		var attids = document.getElementById('attachmentids');
		if (attids.value.indexOf(docid) == -1) {
			attids.value = attids.value + docid + ',';
		}
	},
	deleteAttachment : function (docid, ele) {
		var attids = document.getElementById('attachmentids');
		attids.value = attids.value.replace(docid+',', '');
		var attcnt = document.getElementById('attachmentCount');
		attcnt.value = attcnt.value-1;
	},
	progress_show: function (msg, suffix) {
		if (typeof(suffix) == 'undefined') {
			suffix = '';
		}
		VtigerJS_DialogBox.block();
		if (typeof(msg) != 'undefined') {
			jQuery('#_progressmsg_').html(msg + suffix.toString());
		}
		jQuery('#_progress_').show();
	},
	progress_hide: function () {
		VtigerJS_DialogBox.unblock();
		jQuery('#_progressmsg_').html('');
		jQuery('#_progress_').hide();
	},
	show_error: function (message) {
		ldsModal.show(alert_arr['ERROR'], DOMPurify.sanitize(message), 'small', '');
	},
	hide_error: function () {
		setTimeout(
			function () {
				ldsModal.close();
			},
			5000
		);
	},
	show_message: function (message) {
		ldsModal.show('', DOMPurify.sanitize(message), 'small', '');
		attachmentManager.hide_error();
	},
	i18n: function (key) {
		if (typeof(alert_arr) != 'undefined' && alert_arr[key]) {
			return alert_arr[key];
		}
		return key;
	},
	placeAtCenter : function (element) {
		element.css('position', 'absolute');
		element.css('top', ((jQuery(window).height() - element.outerHeight()) / 2) + jQuery(window).scrollTop() + 'px');
		element.css('left', ((jQuery(window).width() - element.outerWidth()) / 2) + jQuery(window).scrollLeft() + 'px');
	},
	getDocuments : function () {
		if (!attachmentManager.checkUploadCount()) {
			return false;
		}
		window.open('index.php?module=Documents&return_module=MailManager&action=Popup&popuptype=detailview&form=EditView&form_submit=false&recordid=&forrecord=&srcmodule=MailManager&popupmode=ajax&RLreturn_module=MailManager&callback=MailManager.add_data_to_relatedlist', 'test', cbPopupWindowSettings);
	},
	checkUploadCount : function () {
		var CurrentUploadCount = jQuery('#attachmentCount').val();
		if (CurrentUploadCount >= attachmentManager.UploadLimit) {
			attachmentManager.show_error(attachmentManager.i18n('JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'));
			return false;
		}
		return true;
	}
};
jQuery(document).ready(function () {
	attachmentManager.createUploader();
	if (__attinfo.length>0) {
		var dzelem = document.getElementById('file-uploader');
		for (var i=0; i<__attinfo.length; i++) {
			dzelem.dropzone.emit('addedfile', {name:__attinfo[i]['name'], size:__attinfo[i]['size'], docid:__attinfo[i]['docid']});
			dzelem.dropzone.emit('complete', {name:__attinfo[i]['name'], size:__attinfo[i]['size'], docid:__attinfo[i]['docid']});
		}
	}
});