const fieldtypes = [{
	type: 'Uitype',
	values: {
		1: mod_alert_arr.LineText,
		21: mod_alert_arr.BlockTextSmall,
		19: mod_alert_arr.BlockTextLarge,
		4: mod_alert_arr.AutoGenerated,
		5: mod_alert_arr.Date,
		50: mod_alert_arr.DateTime,
		14: mod_alert_arr.Time,
		7: mod_alert_arr.Number,
		71: mod_alert_arr.Currency,
		9: mod_alert_arr.Percentage,
		10: mod_alert_arr.RelationModule,
		101: mod_alert_arr.RelationUsers,
		11: mod_alert_arr.Phone,
		13: mod_alert_arr.Email,
		17: mod_alert_arr.URL,
		56: mod_alert_arr.Checkbox,
		69: mod_alert_arr.Image,
		85: mod_alert_arr.Skype,
		15: mod_alert_arr.SelectWithRole,
		16: mod_alert_arr.Select,
		1613: mod_alert_arr.SelectModules,
		1024: mod_alert_arr.SelectRoles,
		33: mod_alert_arr.SelectMultiple,
		3313: mod_alert_arr.SelectModulesMultiple,
	
	}
},
{
	type: 'Presence',
	values: {
		0: mod_alert_arr.AlwaysActive,
		1: mod_alert_arr.InactiveActive,
		2: mod_alert_arr.ActiveActive,
	}
},
{
	type: 'Quickcreate',
	values: {
		0: mod_alert_arr.AlwaysShownNoDeactivate,
		1: mod_alert_arr.NotShownCanBeActivated,
		2: mod_alert_arr.ShownCanBeDeactivated,
		3: mod_alert_arr.NotShownCanNotBeActivated,
	}
},
{
	type: 'Displaytype',
	values: {
		1: mod_alert_arr.DisplayEverywhere,
		2: mod_alert_arr.ReadOnly,
		3: mod_alert_arr.DisplayByProgrammer,
		4: mod_alert_arr.ReadOnlyModifyWorkflow,
		5: mod_alert_arr.DisplayCreate,
	}
},
{
	type: 'Masseditable',
	values: {
		0: mod_alert_arr.NoMassEditNoActivate,
		1: mod_alert_arr.MassEditable,
		2: mod_alert_arr.NoMassEditActivate,
	}
}];

const checkboxFields = [{
	type: 'Typeofdata',
	value: 'Mandatory',
}];

const textfields = [
	'fieldname',
	'columnname',
	'fieldlabel',
	'entityidentifier',
	'relatedmodules',
	'sequence'
];

const setdefaultOption = [{
	false: alert_arr.NO,
	true:  alert_arr.YES,
}];