name: formatting_unittests
on: [push]
jobs:
  formatcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t tsolucio/corebos-formatter -f ./docker/Dockerfile .
      - name: run php formatting
        run: docker run tsolucio/corebos-formatter phpcs.phar --standard=build/cbSR/ci.xml --extensions=inc,js,php,service `cat build/cbSR/cifiles build/cbSR/cifiles.custom`
      - name: run js formatting
        run: docker run tsolucio/corebos-formatter eslint -c build/cbSR/eslintci.js `cat build/cbSR/cifilesjs build/cbSR/cifilesjs.custom`
      - name: find
        run: docker run tsolucio/corebos-formatter find . -not -path "./.git/*" -type f -perm /u=x,g=x,o=x -print | sort -f | diff build/cbSR/executables -
      - name: check syntax
        run: docker run tsolucio/corebos-formatter build/cbSR/chksyntax
  
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t tsolucio/corebosunittest -f ./docker/Dockerfileunittest . 
      - name: start corebos and run unit tests
        run: docker run -t tsolucio/corebosunittest ./run.sh
