/*********************************************************************************
** The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger. All Rights Reserved.
 * Contributor(s): Valmir Carlos Trindade/Translate to Brazilian Portuguese|01/03/2012|Curitiba/Paraná/Brasil.|www.ttcasolucoes.com.br
 ********************************************************************************/

var alert_arr = {
	'DELETE':'Deseja realmente apagar o registro selecionado?',
    'RECORDS':' registros!',
    'SELECT':'Por favor, selecione pelo menos uma entidade',
    'DELETE_ACCOUNT':'Ao apagar esta(s) Organização(s) serão removidas as Cotações e Oportunidades relacionadas. Deseja realmente apagar? ',
    'DELETE_VENDOR':'Ao apagar este(s) Fornecedor(s) serão removidos os Pedidos de Compras relacionados. Deseja realmente apagar? ',
    'SELECT_MAILID':'Por favor, selecione uma mensagem',
    'OVERWRITE_EXISTING_ACCOUNT1':'Sobrescrever o endereço existente com o desta Organização selecionada(',
    'OVERWRITE_EXISTING_ACCOUNT2':') detalhes do endereço?',
    'OVERWRITE_EXISTING_CONTACT1':'Sobrescrever o endereço existente com o deste Contato selecionado(',
    'OVERWRITE_EXISTING_CONTACT2':') detalhes do endereço?',
    'MISSING_FIELDS':'Campos requeridos ausentes:',
    'NOT_ALLOWED_TO_EDIT':'você não tem permissão para editar este campo',
    'NOT_ALLOWED_TO_EDIT_FIELDS':'você não tem permissão para o(s) campo(s)',
    'COLUMNS_CANNOT_BE_EMPTY':'A coluna selecionada não pode estar vazia',
    'CANNOT_BE_EMPTY':' não pode estar vazio',
    'CANNOT_BE_NONE':' não pode ser nula',
    'ENTER_VALID':'Por favor, digite um registro válido ',
    'SHOULDBE_LESS':' deve ser menos que ',
    'SHOULDBE_LESS_EQUAL':' deve ser menos que ou igual a ',
    'SHOULDBE_EQUAL':' deve ser igual a ',
    'SHOULDBE_GREATER':' deve ser maior que ',
    'SHOULDBE_GREATER_EQUAL':' deve ser maior que ou igual a ',
    'INVALID':'Inválido ',
    'EXCEEDS_MAX':' limite máximo excedido ',
    'OUT_OF_RANGE':' está fora do limite',
    'SHOULDNOTBE_EQUAL':' não deve ser igual a ',
    'PORTAL_PROVIDE_EMAILID':'Por gentileza, forneça um e-mail válido para habilitar Usuário Portal',
    'ADD_CONFIRMATION':'Deseja realmente adicionar o registro selecionado ',
    'ACCOUNTNAME_CANNOT_EMPTY':'AccountName não pode estar vazio',
    'CANT_SELECT_CONTACTS':"você não pode selecionar Contatos relacionados do Lead",
    'LBL_THIS':'Este ',
    'DOESNOT_HAVE_MAILIDS':"não tem nenhum e-mail",
    'ARE_YOU_SURE':'você tem certeza?',
    'DOESNOT_HAVE_AN_MAILID':'" '+"não tem uma identificação do e-mail",
    'MISSING_REQUIRED_FIELDS':'Campos requeridos ausentes: ',
    'READONLY':"somente para leitura",
    'SELECT_ATLEAST_ONE_USER':'Por favor, selecione pelo menos um Usuário',
    'DISABLE_SHARING_CONFIRMATION':'Deseja realmente desabilitar compartilhamento para o registro selecionado?',
    'USERS':' Usuário(s) ?',
    'ENDTIME_GREATER_THAN_STARTTIME':'Hora Final deve ser maior que a Hora Inicial ',
    'FOLLOWUPTIME_GREATER_THAN_STARTTIME':'Hora do Followup deve ser maior que Hora Final ',
    'MISSING_EVENT_NAME':'Nome do Evento ausente',
    'EVENT_TYPE_NOT_SELECTED':'Tipo Evento não está selecionado',
    'CLOSEDATE_CANNOT_BE_EMPTY':'Campo Data Fechamento não pode estar vazio',
    'SITEURL_CANNOT_BE_EMPTY':'URL do Site não pode estar vazia',
    'SITENAME_CANNOT_BE_EMPTY':'Nome do Site não pode estar vazio',
    'LISTPRICE_CANNOT_BE_EMPTY':'Lista de Preços não pode estar vazia',
    'INVALID_LIST_PRICE':'Lista de Preços inválida',
    'PROBLEM_ACCESSSING_URL':'Problema acessando a URL: ',
    'CODE':' Código: ',
    'WISH_TO_QUALIFY_MAIL_AS_CONTACT':'Deseja realmente Qualificar esta Mensagem como Contato?',
    'SELECT_ATLEAST_ONEMSG_TO_DEL':'Por favor, selecione pelo menos uma mensagem para apagar',
    'ERROR':'Erro',
    'FIELD_TYPE_NOT_SELECTED':'O Tipo de Campo não está selecionado',
    'SPECIAL_CHARACTERS_NOT_ALLOWED':'Caracteres Especiais não são permitidos no campo Rótulo',
	'SPECIAL_CHARACTERS':'Caracteres Especiais',
    'NOT_ALLOWED':'não são permitidos. Por gentileza, tente outro valor',
    'PICKLIST_CANNOT_BE_EMPTY':'Valor da Lista de Opções não pode estar vazio',
    'DUPLICATE_VALUES_FOUND':'Encontrado valor duplicado',
    'DUPLICATE_MAPPING_ACCOUNTS':'Duplicar mapeamento para Organizações!!',
    'DUPLICATE_MAPPING_CONTACTS':'Duplicar mapeamento para Contatos!!',
    'DUPLICATE_MAPPING_POTENTIAL':'Duplicar mapeamento para Oportunidades!!',
    'ERROR_WHILE_EDITING':'Erro durante Edição',
    'CURRENCY_CHANGE_INFO':'Mudanças na Moeda realizadas com Sucesso!!',
    'CURRENCY_CONVERSION_INFO':'você deseja utilizar o Dolar US$ como Moeda? \n Clique OK para permanecer como US$, Cancelar para mudar taxa de câmbio da Moeda.',
    'THE_EMAILID': "O ID do e-mail\'",
    'EMAIL_FIELD_INVALID':"\' no campo do e-mail é inválido",
    'MISSING_REPORT_NAME':'Nome do Relatório ausente',
    'REPORT_NAME_EXISTS':'Nome do Relatório já existe, tente novamente...',
    'WANT_TO_CHANGE_CONTACT_ADDR':'Deseja mudar o endereço do Contato relacionado com esta Organização?',
    'SURE_TO_DELETE':'Deseja realmente apagar ?',
    'NO_PRODUCT_SELECTED':'Nenhum produto foi selecionado. Selecione pelo menos um Produto',
    'VALID_FINAL_PERCENT':'Digite percentual de Desconto Final válido',
    'VALID_FINAL_AMOUNT':'Digite o Total do Desconto Final',
    'VALID_SHIPPING_CHARGE':'Digite um valor do Frete válido',
    'VALID_ADJUSTMENT':'Digite um Ajuste válido',
    'WANT_TO_CONTINUE':'Deseja Continuar?',
    'ENTER_VALID_TAX':'Por favor, digite um valor do Imposto válido',
    'VALID_TAX_NAME':'Digite um nome de Imposto válido',
    'CORRECT_TAX_VALUE':'Digire valor do Imposto correto',
    'ENTER_POSITIVE_VALUE':'Por favor, digite um valor positivo',
    'LABEL_SHOULDNOT_EMPTY':'O nome do Rótulo do Imposto não pode estar vazio',
    'NOT_VALID_ENTRY':'não é uma entrada válida. Por favor, digite o valor correto',
    'VALID_DISCOUNT_PERCENT':'Digite um percentual de Desconto válido',
    'VALID_DISCOUNT_AMOUNT':'Digite um total de Desconto válido',
    'SELECT_TEMPLATE_TO_MERGE':'Por favor, selecione um modelo para mesclar',
    'SELECTED_MORE_THAN_ONCE':'você selecionou o(s) seguinte(s) produto(s) mais de uma vez.',
    'YES':'sim',
    'NO':'não',
    'MAIL':'correio',
    'EQUALS':'igual',
    'NOT_EQUALS_TO':'diferente de',
    'STARTS_WITH':'iniciar com',
    'CONTAINS':'contem',
    'DOES_NOT_CONTAINS':'não contem',
    'LESS_THAN':'menor que',
    'GREATER_THAN':'maior que',
    'LESS_OR_EQUALS':'menor ou igual',
    'GREATER_OR_EQUALS':'maior ou igual',

    'NO_SPECIAL_CHARS':'Caracteres Especiais não são permitos na String da Fatura',
    'PLS_SELECT_VALID_FILE':'Por favor, selecione um arquivo com a seguinte extensão:\n',
    'NO_SPECIAL':'Caracteres Especiais não são permitidos',
	'NO_QUOTES':'Cotações (\' ") e símbolo + não são permitidos ',
    'IN_PROFILENAME':' no Nome do Perfil',
    'IN_GROUPNAME':' no Nome do Grupo',
    'IN_ROLENAME':' no Nome da Função',
    'VALID_TAX_PERCENT':'Digite um percentual de Imposto válido',
    'VALID_SH_TAX':'Digite um imposto válido para Fretes ',
    'ROLE_DRAG_ERR_MSG':'você não pode mover um Nó Pai sob um Nó Filho',
    'LBL_DEL':'apagar',
    'VALID_DATA':' Digite dados válidos, por favor, tente novamente... ',
    'STDFILTER': 'Filtros Padrões',
    'STARTDATE': 'Data Inicial',
    'ENDDATE': 'Data Final',
    'START_DATE_TIME': 'Data e Hora Inicial',
    'START_TIME': 'Hora Inicial',
    'DATE_SHOULDNOT_PAST':'Data e hora atuais para Atividades com status Planejado',
    'TIME_SHOULDNOT_PAST':'Data atual para Atividades com status Planejado',
    'LBL_AND': 'E',
    'LBL_OR': 'Ou',
    'LBL_ENTER_VALID_PORT': 'Por favor, digite um número de porta válido',
    'IN_USERNAME':' em Nome Usuário ',
    'LBL_ENTER_VALID_NO': 'Por favor, digite um número válido',
    'LBL_PROVIDE_YES_NO': ' Valor inválido.\n Por favor, informe Sim ou não',
    'LBL_SELECT_CRITERIA': ' Critério inválido.\n Por favor selecione o critério',
    // Added/Updated for vtiger CRM 5.0.4
    'OPPORTUNITYNAME_CANNOT_BE_EMPTY':'O campo Nome Oportunidade não pode estar vazio',
    'OVERWRITE_EXISTING_ACCOUNT1':'você deseja Sobrescrever o endereço atual por este da Organização selecionada(',
    'NAME_DESC':' para Nome Pasta & Descrição',
    'ENDS_WITH':'finais com',
    'SHARED_EVENT_DEL_MSG':'O Usuário não tem permissão para Editar/Apagar Evento Compartilhado.',

    'LBL_WRONG_IMAGE_TYPE': 'Tipos de arquivos permitidos para Contatos - jpeg, png, jpg, pjpeg, x-png ou gif',
    'SELECT_MAIL_MOVE': 'Por favor, selecione uma mensagem e então mova..',
	
	'LBL_NOTSEARCH_WITHSEARCH_ALL':'você não utilizou a pesquisa. Todos os dados serão Exportados em',
    'LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE':'você não pesquisou nada. Mas selecionou com Opções de página search&current. Desta forma os registros na página atual serão Exportados em',
    'LBL_NO_DATA_SELECTED':'Nenhum registro selecionado. Selecione pelo menos um resgistro para Exportar',
    'LBL_SEARCH_WITHOUTSEARCH_ALL':'você utilizou a opção pesquisar mas não selecionou as Opções pesquisar & todos.\nvocê pode clicar em [ok] para exportar todos os dados ou pode clicar em [cancelar] e tentar novamente outro critério para exportar',
    'STOCK_IS_NOT_ENOUGH': 'A quantidade em Estoque não é suficiente',
    'LBL_QTY_IN_STOCK' : 'Qde em Estoque',
    'INVALID_QTY': 'Qde. inválida',
    'LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE':'você utilizou a opção pesquisar mas não selecionou as Opções pesquisa & página atual.\nvocê pode clicar em [ok] para exportar os dados da página atual ou\n você pode clicar em [cancelar] e tentar novamente outro critério para exportar.',
    'LBL_SELECT_COLUMN': ' Coluna inválida.\n Por gentileza, selecione a coluna',
    'LBL_NOT_ACCESSIBLE': 'não Acessível',
	'LBL_FILENAME_LENGTH_EXCEED_ERR': 'Nome do arquivo não pode exceder a 255 caracteres',
	'LBL_DONT_HAVE_EMAIL_PERMISSION': "você não tem permissão para campo Email, portanto não poderá selecionar o e-mail",
	'LBL_NO_FEEDS_SELECTED': 'Nenhum Alimentador Selecionado',
	'LBL_SELECT_PICKLIST':'Por favor, selecione pelo menos um valor para apagar',
	'LBL_CANT_REMOVE':'você não pode remover todos os valores',
	
	/*For global add/delete in picklist*/
	'LBL_GIVE_PICKLIST_VALUE':'Por gentileza, forneça um valor para a Lista de Opções selecionada ser substituída',
	'LBL_SELECT_ROLE':'Por gentileza, selecione pelo menos uma Função para a qual o novo valor será adicionado',
	'LBL_ADD_PICKLIST_VALUE':'Por gentileza, forneça pelo menos um novo valor para ser adicionado',
	'LBL_NO_VALUES_TO_DELETE': "nenhum valor para apagar",

	/* For Duplicate merging feature */
	'SAME_GROUPS': 'você terá que selecionar um registro de em um mesmo grupo para mesclar',
	'ATLEAST_TWO': 'Selecione pelo menos dois registros para mesclar',
	'MAX_THREE': 'você tem permissão para selecionar no máximo três registros',
	'MAX_RECORDS': 'você tem permissão para selecionar no máximo quatro registros',
	'CON_MANDATORY': 'Selecione o campo obrigatório Sobrenome',
	'LE_MANDATORY': 'Selecione os campos obrigatórios Sobrenome e Empresa',
	'ACC_MANDATORY': 'Selecione o campo obrigatório Organização',
	'PRO_MANDATORY': 'Selecione o campo obrigatório Produto',
	'TIC_MANDATORY': 'Selecione o campo obrigatório Ticket',
	'POTEN_MANDATORY': 'Selecione o campo obrigatório Oportunidade',
	'VEN_MANDATORY': 'Selecione o campo obrigatório Fornecedor',
	'DEL_MANDATORY': 'você não tem permissão para apagar o campo obrigatório',

	/* For Multi-Currency Support */
	'MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE': 'O Preço Unitário de todas as Moedas serão corrigidos tomando-se por base a Moeda selecionada. você confirma?',
	'Select_one_record_as_parent_record': 'Selecionar um registro como registro pai',
	'RECURRING_FREQUENCY_NOT_PROVIDED': 'Frequencia retorno não fornecida',
	'RECURRING_FREQNECY_NOT_ENABLED': 'Frequência retorno fornecida, mas retorno não está habilitado',
	/* Added for Documents module */
	'NO_SPECIAL_CHARS_DOCS':'Caracteres especiais tais como aspas, contrabarra, símbolo de +, % e ? não são permitidos',
	'FOLDER_NAME_TOO_LONG':'Nome Pasta é muito longo. Tente novamente!',
	'FOLDERNAME_EMPTY':'O nome da Pasta não pode estar vazio',
	'DUPLICATE_FOLDER_NAME':'você está tentando duplicar um nome de Pasta existente. Por gentileza, tente novamente!',
	'FOLDER_DESCRIPTION_TOO_LONG':'Descrição da Pasta é muito longa. Tente novamente!',
	'NOT_PERMITTED':"você não tem permissão para executar esta operação.",
	'ALL_FILTER_CREATION_DENIED':'não é possível criar Visualização Customizada utilizando "Todos", tente utilizar condição diferente',
	'OPERATION_DENIED':'você não tem permissão para realizar esta operação',
	'EMAIL_CHECK_MSG': 'Desabilitar acesso ao Portal para salvar o campo de e-mail como em branco',
	'IS_PARENT': 'Este Produto possui Sub Produtos, você não tem permissão para selecionar um Pai para este Produto',

	/*global actions on picklist*/
	'PICKLIST_CANNOT_BE_EMPTY': 'A Lista de Opções não pode estar vazia',
	'DUPLICATE_VALUES_FOUND': 'Valores Duplicados encontrados',
	'LBL_NO_ROLES_SELECTED': 'Nenhuma Função foi selecionada, você deseja continuar?',
	'LBL_DUPLICATE_FOUND': 'Entrada duplicada encontrada para o valor ',
	'LBL_CANNOT_HAVE_EMPTY_VALUE': 'não é permitido valor vazio. Para apagar retorne e clique sobre o botão apagar',
	'LBL_DUPLICATE_VALUE_EXISTS': 'Existe valor duplicado',
	'LBL_WANT_TO_DELETE': "Esta ação apagará o(s) valor(es) da Lista de Opções selecionada para todas as Funções. Tem certeza que deseja continuar? ",
	'LBL_DELETE_ALL_WARNING': "você selecionou todos os valores para serem apagados. você deseja continuar?",
	'LBL_PLEASE_CHANGE_REPLACEMENT': "por gentileza, altere o valor substituido; ele também foi selecionado para ser apagado",

	/*layout Editor changes*/
	'BLOCK_NAME_CANNOT_BE_BLANK': 'Nome do Bloco não pode ficar em branco',
	'ARE_YOU_SURE_YOU_WANT_TO_DELETE': 'você tem certeza que deseja apagar ?',
	'PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK': 'Por gentileza, mova o campo para outro Bloco',
	'ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK': 'você tem certeza que deseja apagar o Bloco?',
	'LABEL_CANNOT_NOT_EMPTY': 'O Rótulo não pode ficar em branco',
	'LBL_TYPEALERT_1': 'Desculpe, você não pode mapear o',
	'LBL_WITH': 'com',
	'LBL_TYPEALERT_2': 'tipo de dados. Por gentileza, mapeie os mesmos tipos de dados.',
	'LBL_LENGTHALERT': 'Desculpe, você não pode mapear campos com tamanho de caracteres diferentes. Mapeie os dados com pelo menos o mesmo tamanho de caracteres. ',
	'LBL_DECIMALALERT': 'Desculpe, você não pode mapear campos com casas decimais diferentes. Mapeie os dados com pelo menos o mesmo número de casas decimais.',
	'PICKLIST2PICKLISTALERT': 'Please make sure both picklists share the same values',
	'PICKLIST2TEXTALERT': 'Please make sure the destination text field can hold the longest picklist value',
	'FIELD_IS_MANDATORY': 'Campo obrigatório',
	'FIELD_IS_ACTIVE': 'O Campo está disponível para uso',
	'FIELD_IN_QCREATE': 'Presente no Criar Rápido',
	'FIELD_IS_MASSEDITABLE': 'disponível para Edição em Massa',

	'IS_MANDATORY_FIELD': 'é Campo obrigatório',
	'CLOSEDATE_CANNOT_BE_EMPTY': 'Fechando Dados não pode estar em branco',
	'AMOUNT_CANNOT_BE_EMPTY': 'Valor não pode estar em branco',
	'ARE_YOU_SURE': 'Tem certeza que deseja apagar?',
	'LABEL_ALREADY_EXISTS': 'O Rótulo já existe. Por gentileza, especifique um Rótulo diferente',
	'LENGTH_OUT_OF_RANGE': 'O comprimento do Bloco deve ter menos de 50 caracteres',
	'LBL_SELECT_ONE_FILE': 'Por gentileza, selecione pelo menos um Arquivo',
	'LBL_UNABLE_TO_ADD_FOLDER': 'Impossível adicionar Pasta. Por favor, tente novamente.',
	'LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER': 'Tem certeza que deseja apagar a Pasta?',
	'LBL_ERROR_WHILE_DELETING_FOLDER': 'Erro enquanto a Pasta era apagada. Por favor, tente novamente.',
	'LBL_FILE_CAN_BE_DOWNLOAD': 'O Arquivo está disponível para Download',
	'LBL_DOCUMENT_LOST_INTEGRITY':'Estes Documentos não estão disponíveis. Ele será marcado como Inativo',
	'LBL_DOCUMENT_NOT_AVAILABLE': 'Este Documento não está disponível para Download',
	'LBL_FOLDER_SHOULD_BE_EMPTY': 'A Pasta deve estar limpa para ser removida!',

	'LBL_PLEASE_SELECT_FILE_TO_UPLOAD': 'Por gentileza, selecione o Arquivo para transferência.',
	'LBL_ARE_YOU_SURE_TO_MOVE_TO': 'Tem certeza que desenja mover o(s) Arquivo(s) para ',
	'LBL_FOLDER': ' Pasta',
	'LBL_UNABLE_TO_UPDATE': 'Impossível atualizar! Por favor, tente novamente.',
	'LBL_BLANK_REPLACEMENT': "não é permitido selecionar valores em branco para substituição",
				
	'LBL_IMAGE_DELETED': 'Imagem Apagada',

	/* Tooltip management */
	'ERR_FIELD_SELECTION': 'Algum erro na seleção do campo',

	/* Inventory validation strings */
	'NO_LINE_ITEM_SELECTED': 'Nenhum item da linha foi selecionado. Por favor, selecione pelo menos um item da linha.',
	'LINE_ITEM': 'Item Linha',
	'LIST_PRICE': 'Lista Preço',

	/* Webmails */
	'LBL_PRINT_EMAIL': 'Imprimir',
	'LBL_DELETE_EMAIL': 'Apagar',
	'LBL_DOWNLOAD_ATTACHMENTS': 'Download Anexos',
	'LBL_QUALIFY_EMAIL': 'Qualificar',
	'LBL_FORWARD_EMAIL': 'Encaminhar',
	'LBL_REPLY_TO_SENDER': 'Responder Remetente',
	'LBL_REPLY_TO_ALL': 'Responder Todos',

	'LBL_WIDGET_HIDDEN': 'Widget Ocultado',
	'LBL_RESTORE_FROM_PREFERENCES': ' Você poderá restaura-lo em Minhas Preferências',
	'ERR_HIDING': 'Erro enquanto ocultava',
	'MSG_TRY_AGAIN': 'Por favor, tente novamente',

	'MSG_ENABLE_SINGLEPANE_VIEW': 'Habilitar Visualização Monolí­tica',
	'MSG_DISABLE_SINGLEPANE_VIEW': 'Desabilitar Visualização Monolí­tica',

	'MSG_FTP_BACKUP_DISABLED': 'Desabilitar Backup FTP',
	'MSG_LOCAL_BACKUP_DISABLED': 'Backup Local Desabilitado',
	'MSG_FTP_BACKUP_ENABLED': 'Backup FTP Habilitado',
	'MSG_LOCAL_BACKUP_ENABLED': 'Backup Local Habilitado',
	'MSG_CONFIRM_PATH': 'confirme com os detalhes do Path',
	'MSG_CONFIRM_FTP_DETAILS': 'confirme com os detalhes do FTP',

	'START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY': 'Período inicial ou final não pode estar vazio',
				
	/* added to fix i18n issues with home page*/
	'LBL_ADD': 'Adicionar ',
	'Module': 'Módulo',
	'DashBoard': 'Painel',
	'RSS': 'RSS',
	'Default': 'Padrão',
	'Notebook': 'Bloco Notas',
	'ReportCharts': 'Gráficos Relatórios',
	'SPECIAL_CHARS':'\\ / < > + \' " ',
				
	'BETWEEN': 'entre',
	'BEFORE': 'antes',
	'AFTER': 'depois',
	'ERROR_DELETING_TRY_AGAIN': 'Erro durante processo de apagar. Por favor, tente novamente.',
	'LBL_ENTER_WINDOW_TITLE': 'Por favor, digite Título Janela.',
	'LBL_SELECT_ONLY_FIELDS': 'Por favor, selecione somente dois campos.',
	'LBL_ENTER_RSS_URL':'Por favor, digite a URL RSS',
	'LBL_ADD_HOME_WIDGET': 'Não é possível adicionar! Por favor, tente novamente',
	
	'LBL_DEFAULT_VALUE_FOR_THIS_FIELD' : 'Valor padrão para este Campo',

	'RECIPIENTS_CANNOT_BE_EMPTY' : 'Remetente selecionado não pode estar vazio',
	'VALID_SCANNER_NAME' : 'Por favor, digite um nome de Scanner válido (Deve ser somente Números e Caracteres)',
	'ERR_SAME_SOURCE_AND_TARGET' : 'O campo de Origem e o de Destino não devem se os mesmos',
	'ERR_ATLEAST_ONE_VALUE_FOR' : 'Você precisa selecionar pelo menos um valor',
	'ERR_SELECT_MODULE_FOR_DEPENDENCY' : 'Por favor, selecione um módulo para adicionar Dependência',

	'LBL_SIZE_SHOULDNOTBE_GREATER':'O tamanho do arquivo não pode ser maior do que ', //added for upload error message
	'LBL_MAX_SIZE':'O tamanho máximo de upload é de ', //added for display file size limit
	'LBL_FILESIZEIN_MB':'MB', // added to show filesize limit in MB
	'LBL_FILESIZEIN_KB':'KB', // added to show filesize limit in KB
	'LBL_FILESIZEIN_B':'B', // added to show filesize limit in B
	//Contexual help page
    'LBL_HELP_TITLE': 'Ajuda',
    'LBL_WIKI_TITLE': 'Manuais',
    'LBL_FAQ_TITLE': 'FAQ',
    'LBL_VIDEO_TITLE': 'Video',
    'LBL_CLOSE_TITLE': 'Fechar',
    'LBL_SELECT':'Selecionar o Widgets Padrão para ser mostrado',

	'ERR_SELECT_ATLEAST_ONE_MERGE_CRITERIA_FIELD' : 'Selecionar pelo menos um campo para os critérios de mesclagem',
	'ERR_PLEASE_MAP_MANDATORY_FIELDS' : 'Por favor, mapeie os seguintes campos obrigatórios',
	'ERR_MAP_NAME_ALREADY_EXISTS' : 'O nome do mapeamento já existe. Por favor, dê um nome diferente',
	'ERR_MAP_NAME_CANNOT_BE_EMPTY' : 'O nome do mapeamento não pode estar vazio',
	'ERR_FIELDS_MAPPED_MORE_THAN_ONCE' : 'Os seguintes campos estão mapeados mais de um vez. Por favor, verifique o mapeamento.',
	'LBL_MERGE_SHOULDHAVE_INFO' : 'Selecionar pelo menos um campo para o critério de mesclagem',
	'MAP_NAME_EXISTS' : 'Este nome de mapa já existe. \n Você quer sobrescrever?',
	'MAP_DELETED_INFO' : 'Este mapa foi deletado. Você não pode utilizar este map novamente',

	//arror messages for lead conversion
	'ERR_SELECT_EITHER':'Selecione uma Organização ou Contato para converter o Lead',
	'ERR_SELECT_ACCOUNT':'Selecione Organização para prosseguir',
	'ERR_SELECT_CONTACT':'Selecione Contato para prosseguir',
	'ERR_MANDATORY_FIELD_VALUE':'Estão faltando valores para Campos Obrigatórios',
	'ERR_POTENTIAL_AMOUNT':'O valor da Oportunidade deve ser um número',
	'ERR_EMAILID':'Digite um Email válido',
	'ERR_TRANSFER_TO_ACC':'A Organização deve ser selecionada para transferir os registros relacionados',
	'ERR_TRANSFER_TO_CON':'O Contato deve ser selecionado paa transferir os registros relacionados',
	'SURE_TO_DELETE_CUSTOM_MAP':'Tem certeza que deseja apagar o Mapeamento de Campos?',
	'LBL_CLOSE_DATE':'Feche Dados',
	'LBL_EMAIL':'Email',
	'MORE_THAN_500' : 'Você selecionou mais de 500 registros. Esta ação poderá demorar muito tempo. Tem certeza que deseja prosseguir?',
	'LBL_MAPPEDALERT':'O campo já foi mapeado',
	'LBL_REPORT_NAME': 'Please enter a name for the new report.',
	'LBL_REPORT_NAME_ERROR': 'You must give a new name to the report.',
	'LBL_IS' : 'is',
	'LBL_CONTAINS': 'contains',
	'LBL_DOES_NOT_CONTAIN' : 'does not contain',
	'LBL_STARTS_WITH' : 'starts with',
	'LBL_ENDS_WITH' : 'ends with',
	'LBL_HAS_CHANGED' : 'has changed',
	'LBL_HAS_CHANGED_TO' : 'has changed to',
	'LBL_IS_EMPTY': 'is empty',
	'LBL_IS_NOT_EMPTY' : 'is not empty',
	'LBL_EQUAL_TO' : 'equal to',
	'LBL_LESS_THAN' : 'less than',
	'LBL_GREATER_THAN' : 'greater than',
	'LBL_DOEST_NOT_EQUAL' : 'does not equal',
	'LBL_LESS_THAN_OR_EQUAL_TO' : 'less than or equal to',
	'LBL_GREATER_THAN_OR_EQUAL_TO' : 'greater than or equal to',
	'LBL_IS_NOT' : 'is not',
	'LBL_BETWEEN' : 'between',
	'LBL_BEFORE' : 'before',
	'LBL_AFTER' : 'after',
	'LBL_IS_TODAY' : 'is today',
	'LBL_LESS_THAN_DAYS_AGO' : 'less than days ago',
	'LBL_MORE_THAN_DAYS_AGO' : 'more than days ago',
	'LBL_IN_LESS_THAN' : 'in less than',
	'LBL_IN_MORE_THAN' : 'in more than',
	'LBL_DAYS_AGO' : 'days ago',
	'LBL_DAYS_LATER' : 'days later',
	'LBL_LESS_THAN_HOURS_BEFORE' : 'less than hours before',
	'LBL_LESS_THAN_HOURS_LATER' : 'less than hours later',
	'LBL_MORE_THAN_HOURS_BEFORE' : 'more than hours before',
	'LBL_MORE_THAN_HOURS_LATER' : 'more than hours later',
	'LBL_EXISTS' : 'exists',
	'MAXIMUM_OF_TWO_MODULES_PERMITTED' : 'A maximum of two modules is permitted.',
	'LBL_NEW_CONDITION' : 'Nova Condição',
	'WF_UPDATE_MAP_ERROR' : '**ERROR**: This task uses a field that does not exist: ',
	'WF_UPDATE_MAP_ERROR_INFO' : 'The task will load with INCORRECT settings to permit you to fix it. It is NOT CORRECT!!',
	'MoveUp' : 'Move Up',
	'MoveDown' : 'Move Down',
	'Products' : 'Products',
	'Services' : 'Services',
	'LBL_Hide' : 'Ocultar',
	'LBL_Show' : 'Mostrar',
	'ERR_INVALID_DATE_FORMAT' : 'O formato de data deve ser: yyyy-mm-dd',
	'ERR_INVALID_MONTH' : 'Por favor entre com um mês válido.',
	'ERR_INVALID_DAY' : 'Por favor entre com um dia válido.',
	'ERR_INVALID_YEAR' : 'Por favor entre com 4 dígitos válidos para ano.',
	'ERR_INVALID_DATE' : 'Por favor entre com uma data válida.',
	'ERR_INVALID_HOUR' : 'Por favor entre com uma hora válida.',
	'ERR_INVALID_TIME' : 'Por favor entre com horário válido.'
};
